#spring配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useSSL=false
    username: root
    password: root
  redis:
    host: 192.168.9.30
    port: 6379

#redis配置
#  redis:
#    sentinel:
#     master: mymaster
#     nodes: 192.168.9.30:6379



